# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
  # Preserve plain text password in token for refresh the user.
  # Analyze the security considerations before turn off this setting.
  erase_credentials: false

  encoders:
    FOS\UserBundle\Model\UserInterface: bcrypt

#  acl:
#    connection: default

  role_hierarchy:
    ROLE_ADMIN:       ROLE_USER
    ROLE_SUPER_ADMIN: ROLE_ADMIN

  providers:
    chain_provider:
      chain:
        providers: [fos_userbundle, fr3d_ldapbundle]
    fr3d_ldapbundle:
      id: fr3d_ldap.security.user.provider
    fos_userbundle:
      id: fos_user.user_provider.username

  firewalls:
    # no security required for debug paths and static resources
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false

    main:
      json_ldap_login:
          check_path: /zlogin
          username_path: _username
          password_path: _password
      logout: true
      anonymous: ~
#      remember_me:
#        secret: '%secret%'
#        lifetime: 31556926 # 1 year in seconds
#        path: /
#        always_remember_me: true

  access_control:
    - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
#    - { path: ^/admin/, role: ROLE_ADMIN }
