---
- name: Deploy the application
  hosts: dev

  become: yes
  become_user: root
  become_method: sudo

  vars_files:
    - ../vars/dev.yml
    - vars/common.yml
    - vars/dev.yml

  roles:
    - zitec.project_deploy
