services:

    admin.zuser:
        class: AppBundle\Admin\ZUserAdmin
        arguments: [~, AppBundle\Entity\ZUser, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Users }
        public: true

    app.hydrator.zitec_hydrator:
        class: AppBundle\Hydrator\ZitecHydrator
        arguments:
            - "@fos_user.user_manager"
            - "%fr3d_ldap.ldap_manager.parameters%"
            - "@app.hydrator.makeit_communicator"
            - ['%kernel.root_dir%']

    app.hydrator.makeit_communicator:
        class: AppBundle\Hydrator\MakeitCommunicator
        arguments: ['%makeit.config%']