SkillsBundle\Entity\Category:
    type: entity
    id:
        id:
            type: integer
            generator:
              strategy: AUTO

    fields:
        name:
            type: string
            length: 100

    manyToMany:
        skills:
            targetEntity: SkillsBundle\Entity\Skill
            mappedBy: categories
